language: elixir
elixir:
  - 1.6.2
otp_release:
  - 20.2
before_script:
  - mix local.hex --force
  - mix deps.get --only test
  - export CI="true"
script:
  - bin/test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
